function g = glof_coeffs_from_fourier(ell, c, m, alpha, beta, lambda, Q)
%GLOF_COEFFS_FROM_FOURIER  GLOF coefficients from Fourier coefficients.
%
%   g = GLOF_COEFFS_FROM_FOURIER(ell, c, m, alpha, beta, lambda, Q)
%   produces an approximation of the GLOF coefficients
%       g_n = (1/gamma_n) * integral_0^1 f_N^F(x) S_n(x) (-log x)^alpha x^lambda dx,
%             n = 0,...,m,
%   where f_N^F(x) = sum_j c(j) exp(2*pi*i*ell(j)*x) is the truncated
%   Fourier partial sum.
%
%   The integral is evaluated with the Chen--Shen Gauss--GLOF quadrature
%   rule generated by GLOF_QUADRATURE_MATRICES.  No adaptive integral() call
%   is used in the GLOF coefficient computation.
%
%   Input
%       ell    : Fourier mode indices (vector)
%       c      : Fourier coefficients (vector, same length as ell)
%       m      : largest GLOF degree to compute
%       alpha  : Laguerre parameter, alpha > -1
%       beta   : GLOF parameter, beta > -1
%       lambda : weight parameter
%       Q      : number of Gauss--GLOF quadrature points
%
%   Output
%       g : (m+1)-by-1 real vector of GLOF coefficients g_n.

    [xq, Wg, S, ~, ~, ~, gamma_vec] = ...
        glof_quadrature_matrices(Q, m, alpha, beta, lambda);

    Fq = eval_fourier_sum(xq, ell, c);
    g = (S * (Wg(:) .* Fq(:))) ./ gamma_vec(:);
    g = real(g);
end
