function g = glof_coeffs_logsing_stable(r, k, m, alpha, beta, lambda, Q)
%GLOF_COEFFS_LOGSING_STABLE  Stable direct GLOF projection of x^r(-log x)^k.
%
%   g = GLOF_COEFFS_LOGSING_STABLE(r,k,m,alpha,beta,lambda,Q) computes
%   the GLOF projection coefficients of
%
%       f(x) = x^r * (-log x)^k
%
%   without evaluating the coefficient integral at extremely small x.
%   This routine is intended for the analytic model function above.  For a
%   generic function handle, use GLOF_COEFFS_EXACT instead.
%
%   With t = -log(x), theta=(beta-lambda)/2, and
%
%       mu = r + theta + lambda + 1,
%
%   the coefficient integral becomes
%
%       int_0^inf exp(-mu*t) t^(alpha+k)
%           L_n^(alpha)((beta+1)*t) dt.
%
%   For alpha=0, this is evaluated from the Laplace-transform identity
%
%       int_0^inf exp(-mu*t) L_n(a*t) dt = (mu-a)^n / mu^(n+1),
%
%   with the powers t^k generated by differentiating with respect to mu.
%   This avoids the catastrophic cancellation seen when high-order
%   Laguerre polynomials are integrated by direct Gauss-Laguerre sums.
%
%   For alpha ~= 0, the routine falls back to the t-space Gauss-Laguerre
%   rule.  That path is useful for moderate order, but high-order cases may
%   still require a dedicated analytic formula or higher precision.

    if nargin < 7 || isempty(Q)
        Q = max(80, m + k + 20);
    end

    theta = (beta - lambda) / 2;
    mu = r + theta + lambda + 1;

    if mu <= 0
        error('glof_coeffs_logsing_stable:InvalidMu', ...
              'The transformed exponential rate mu must be positive.');
    end

    if alpha == 0 && k == round(k) && k >= 0
        g = coeffs_alpha_zero(r, k, m, beta, mu);
        return;
    end

    g = coeffs_t_space_quadrature(r, k, m, alpha, beta, mu, Q);
end

function g = coeffs_alpha_zero(~, k, m, beta, mu)
    a = beta + 1;
    delta = mu - a;
    gamma_vec = glof_norm_const((0:m).', 0, beta);
    integrals = zeros(m+1, 1);

    for n = 0:m
        integral_n = 0;
        imax = min(k, n);

        for i = 0:imax
            delta_power = n - i;
            if delta == 0 && delta_power > 0
                continue;
            elseif delta_power == 0
                log_delta_power = 0;
            else
                log_delta_power = delta_power * log(abs(delta));
            end

            log_abs = gammaln(k + 1) - gammaln(i + 1) - gammaln(k - i + 1) ...
                    + gammaln(n + k - i + 1) - gammaln(n - i + 1) ...
                    + log_delta_power ...
                    - (n + k + 1 - i) * log(mu);

            term_sign = (-1)^i;
            if delta < 0 && mod(delta_power, 2) == 1
                term_sign = -term_sign;
            end

            integral_n = integral_n + term_sign * exp(log_abs);
        end

        integrals(n+1) = integral_n;
    end

    g = real(integrals ./ gamma_vec(:));
end

function g = coeffs_t_space_quadrature(~, k, m, alpha, beta, mu, Q)
    quad_alpha = alpha + k;
    [s, w] = gauss_laguerre(Q, quad_alpha);

    scaled_arg = ((beta + 1) / mu) * s;
    L = laguerre_matrix(m, alpha, scaled_arg);

    integrals = mu^(-(quad_alpha + 1)) * (L * w(:));
    gamma_vec = glof_norm_const((0:m).', alpha, beta);
    g = real(integrals ./ gamma_vec(:));
end
